# Data Cleaning and Preparation
##### CHAPTER 7

## 7.1 Handling Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [9]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [10]:
string_data.isnull()

0    False
1     True
2     True
3    False
dtype: bool

In [11]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [22]:
data[4] = np.nan
data

     0    1    2   4   4
0  1.0  6.5  3.0 NaN NaN
1  1.0  NaN  NaN NaN NaN
2  NaN  NaN  NaN NaN NaN
3  NaN  6.5  3.0 NaN NaN

In [29]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [30]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [31]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0  0.182943       NaN       NaN
1  0.180244       NaN       NaN
2 -0.562830       NaN  1.377783
3 -1.026747       NaN -0.943074
4 -1.676618 -0.343328  0.254736
5  0.596221 -1.118342  0.576407
6 -0.599286  0.524103 -1.377429

In [32]:
df.dropna()

          0         1         2
4 -1.676618 -0.343328  0.254736
5  0.596221 -1.118342  0.576407
6 -0.599286  0.524103 -1.377429

In [36]:
df.dropna(thresh=2)

          0         1         2
2 -0.562830       NaN  1.377783
3 -1.026747       NaN -0.943074
4 -1.676618 -0.343328  0.254736
5  0.596221 -1.118342  0.576407
6 -0.599286  0.524103 -1.377429

### Filling In Missing Data

In [37]:
df.fillna(0)

          0         1         2
0  0.182943  0.000000  0.000000
1  0.180244  0.000000  0.000000
2 -0.562830  0.000000  1.377783
3 -1.026747  0.000000 -0.943074
4 -1.676618 -0.343328  0.254736
5  0.596221 -1.118342  0.576407
6 -0.599286  0.524103 -1.377429

In [38]:
df.fillna({1:0.5, 2:0})

          0         1         2
0  0.182943  0.500000  0.000000
1  0.180244  0.500000  0.000000
2 -0.562830  0.500000  1.377783
3 -1.026747  0.500000 -0.943074
4 -1.676618 -0.343328  0.254736
5  0.596221 -1.118342  0.576407
6 -0.599286  0.524103 -1.377429

In [39]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [40]:
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan

In [41]:
df

          0         1         2
0 -1.466726  0.118643 -0.049526
1 -0.318654  0.743094 -0.305271
2  2.596069       NaN  0.003476
3  1.832502       NaN  0.417997
4  0.813408       NaN       NaN
5  0.496648       NaN       NaN

In [43]:
df.ffill()

          0         1         2
0 -1.466726  0.118643 -0.049526
1 -0.318654  0.743094 -0.305271
2  2.596069  0.743094  0.003476
3  1.832502  0.743094  0.417997
4  0.813408  0.743094  0.417997
5  0.496648  0.743094  0.417997

In [47]:
df.ffill(limit=2)

          0         1         2
0 -1.466726  0.118643 -0.049526
1 -0.318654  0.743094 -0.305271
2  2.596069  0.743094  0.003476
3  1.832502  0.743094  0.417997
4  0.813408       NaN  0.417997
5  0.496648       NaN  0.417997

In [48]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [49]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64